# Generated by Django 2.1.2 on 2019-02-24 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_comment_reply'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='replied',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
