# Generated by Django 2.1.2 on 2019-03-02 01:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_comment_replied'),
    ]

    operations = [
        migrations.AddField(
            model_name='column',
            name='parent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='column_category', to='blog.Column'),
        ),
    ]
