# Generated by Django 2.1.2 on 2019-03-03 13:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_column_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='column',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='column_category', to='blog.Column'),
        ),
    ]
